application: lunchtracker
version: 1
runtime: python
api_version: 1

handlers:
- url: /img
  static_dir: images

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /.*
  script: lunchtracker.py

- url: /index\.html
  script: lunchtracker.py
